# 项目配置文件
project:
  name: "novel_video_generator"
  version: "1.0.0"
  description: "小说视频生成系统"

# 文件路径配置
paths:
  input_dir: "data/input"
  output_dir: "data/output"
  temp_dir: "data/temp"
  logs_dir: "logs"
  assets_dir: "assets"
  fonts_dir: "assets/fonts"
  templates_dir: "assets/templates"

# 数据库配置
database:
  type: "sqlite"
  path: "data/database/novel_video.db"
  pool_size: 10
  max_overflow: 20

# 日志配置
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  rotation: "100 MB"
  retention: "30 days"
  compression: "zip"

# 豆包统一配置
doubao:
  base_url: "https://ark.cn-beijing.volces.com"
  api_key: "${DOUBAO_API_KEY}"
  model: "doubao-seed-1.6-flash-250615"
  thinking: "disabled"
  max_tokens: 4096
  frequency_penalty: 0
  presence_penalty: 0
  temperature: 1.0
  top_p: 0.7

# 文本转语音配置
tts:
  base_url: "https://openspeech.bytedance.com"
  api_token: "${TTS_TOKEN}"
  id: "${TTS_APP_ID}"
  token: "token"
  cluster: "volcano_tts"
  voice_type: "zh_male_baqiqingshu_mars_bigtts"
  emotion: ""
  enable_emotion: False
  emotion_scale: 4.0
  encoding: "mp3"
  speed_ratio: 1.0
  rate: 24000
  bitrate: 160
  explicit_language: "zh"
  context_language: ""
  loudness_ratio: 1.0
  with_timestamp: 1
  operation: "query"
  disable_markdown_filter: True
  disable_emoji_filter: True

# 图像生成配置
image_gen:
  model: "doubao-seedream-3-0-t2i-250415"
  response_format: "b64_json"
  size: "720x1280"
  seed: 27
  guidance_scale: 9
  watermark: False

# 视频生成配置
video_gen:
  model: "doubao-seedance-1-0-pro-250528"
  callback_url: ""
  resolution: "480p"
  ratio: "9:16"
  duration: 5
  watermark: False
  seed: 27

# 视频处理配置
video:
  fps: 30
  resolution: [1920, 1080]
  codec: "libx264"
  audio_codec: "aac"
  bitrate: "5000k"
  audio_bitrate: "192k"
  preset: "medium"

# 音频配置
audio:
  sample_rate: 44100
  channels: 2
  format: "mp3"

# 任务调度配置
scheduler:
  max_concurrent_tasks: 3
  task_timeout: 3600  # 1小时
  retry_attempts: 3
  retry_delay: 300  # 5分钟

# 分镜脚本配置
storyboard:
  max_scenes_per_chapter: 10
  min_scene_duration: 5
  max_scene_duration: 30
  transition_duration: 1.0

# 文件清理配置
cleanup:
  auto_cleanup: true
  temp_file_retention: 24  # 小时
  output_file_retention: 168  # 7天 